import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KYおすすめ飲食店マップ",
  description: "Generated by create next app",
};

// app/layout.js
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="__app">{children}</div> {/* ルート要素を定義 */}
      </body>
    </html>
  );
}
